version: '3.7'

services:
  minio:
    image: minio/minio:RELEASE.2020-09-26T03-44-56Z
    container_name: tropicalia-minio
    volumes:
      - ./volumes/minio/data:/data
    environment:
      MINIO_ACCESS_KEY: tropicalia
      MINIO_SECRET_KEY: minioS3Cre1K3y
    ports:
      - "9000:9000"
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always